# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
script:
- set -o pipefail && xcodebuild test -workspace Example/RPScanner.xcworkspace -scheme "RPScanner-Example" -configuration "Debug" -destination "platform=iOS Simulator,name=iPhone 6,OS=10.3.1" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
